# Test compose file to run InfluxDB.
# Normally both the sleepy application and InfluxDB would be distinct services in a compose file.
services:
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-conf:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin987654321
      - DOCKER_INFLUXDB_INIT_ORG=sleepy
      - DOCKER_INFLUXDB_INIT_BUCKET=sleepy

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin987654321
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb-data: {}
  influxdb-conf: {}
  grafana-storage: {}
