# GitHub Actions workflow to build and push Docker images to Docker Hub.

# References:
# https://docs.docker.com/build/ci/github-actions/
# https://github.com/marketplace/actions/build-and-push-docker-images

name: Docker build

on:
  push:
    branches:
      - "main"
  workflow_dispatch: # Enable manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sleepy:commit-${{ github.sha }},
                ${{ secrets.DOCKER_USERNAME }}/sleepy:latest
